In [21]:
import numpy as np

def det(A):
    result = 1
    n = len(A)
    # go over all columns k=0,1,...,n-1
    for k in range(n):
        if A[k][k] == 0:
            for i in range(k+1, n):
                if A[i][k] != 0:
                    A[k], A[i] = A[i], A[k]
                    result *= -1
                    break
            else:
                return 0
        # go over all rows i=k+1,k+2,...,n-1
        result *= A[k][k]
        for i in range(k+1, n):
            factor = A[i][k] / A[k][k]
            # go over all the nonzero elements in row i
            for j in range(k, n):
                A[i][j] -= factor * A[k][j]
    return result

A = [[2,8,3],[4,9,1],[3,3,3]]
print(det(A))
print(np.linalg.det(A))

-69.0
-68.99999999999996


In [17]:
print(A)
print(np.linalg.det(A))

[[2 8 3]
 [4 9 1]
 [3 3 3]]
-68.99999999999996


In [ ]:
def det(A):
    n = len(A)
    if n == 1:
        return A[0][0]
    for k in range(n):
        minor_matrix = [[A[i][j] for j in range(n) if j != k] for i in range(1, n)]
        return sum([(-1)**k * A[0][k] * det(minor_matrix) for k in range(n)])
    
#A = np.array([[1,2,3,1],[5,6,7,8],[9,15,11,12],[13,10,15,16]])
A = [[2,8,3],[4,9,1],[3,3,3]]
print(det(A))
print(np.linalg.det(A))

0 [[9, 1], [3, 3]]
0 [[3]]
0 [[3]]
0 [[3]]
-72
-68.99999999999996


In [3]:
A = [[1,2,3], [4,5,6], [7,8,9]]

def det(A):
    result = 1
    n = len(A)
    # go over all columns k=0,1,...,n-1
    for k in range(n):
        if A[k][k] == 0:
            for i in range(k+1, n):
                if A[i][k] != 0:
                    A[k], A[i] = A[i], A[k]
                    result *= -1
                    break
            else:
                return 0
        # go over all rows i=k+1,k+2,...,n-1
        result *= A[k][k]
        for i in range(k+1, n):
            factor = A[i][k] / A[k][k]
            # go over all the nonzero elements in row i
            for j in range(k, n):
                A[i][j] -= factor * A[k][j]
    return result
    


A = np.array([[1,2,3,1],[5,6,7,8],[9,15,11,12],[13,10,15,16]])
A = np.array([[2,8,3],[4,9,1],[3,3,3]])
print(det(A))
print(np.linalg.det(A))

NameError: name 'np' is not defined

In [28]:
def minor(A, i,j):
    B = []
    for k in range(len(A)):
        if k != i:
            B.append([A[k][l] for l in range(len(A)) if l != j])
    return B

def det(A):
    n = len(A)
    if n == 1:
        return A[0][0]
    else:
        sign = 1
        detA = 0
        for i in range(n):
            B = minor(A, 0, i)
            detA += sign*A[0][i]*det(B)
            sign = -sign
        return detA

In [33]:
x = 50000000
#x = 12
a,b,c,d,e,f = 1,x,x,x-1,x-1,2
A = [[0, 1, 1, 1, 1],                   [1, 0, a*a, b*b, c*c],                   [1, a*a, 0, d*d, e*e],                   [1, b*b, d*d, 0, f*f],                   [1, c*c, e*e, f*f, 0]]
#print(np.linalg.det(A))
print(det(A))
print(A)

-32
[[0, 1, 1, 1, 1], [1, 0, 1, 2500000000000000, 2500000000000000], [1, 1, 0, 2499999900000001, 2499999900000001], [1, 2500000000000000, 2499999900000001, 0, 4], [1, 2500000000000000, 2499999900000001, 4, 0]]
